name: ser_manos
description: "An application to apply to voluntary works"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.9.0
  carousel_slider: ^5.0.0
  widget_to_marker: ^1.0.6
  beamer: ^1.6.1
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  custom_lint: ^0.6.7
  firebase_core: ^3.5.0
  build_runner: ^2.4.12
  firebase_auth: ^5.3.0
  riverpod_annotation: ^2.3.5
  firebase_storage: ^12.3.3
  cloud_firestore: ^5.4.4
  freezed_annotation: ^2.4.4
  freezed: ^2.5.7
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  hooks_riverpod: ^2.5.2
  geolocator: ^13.0.1
  image_picker: ^1.0.0
  share_plus: ^10.1.1
  path_provider: ^2.1.4
  http: ^1.2.2
  url_launcher: ^6.3.1
  firebase_remote_config: ^5.1.4
  firebase_analytics: ^11.3.4
  firebase_crashlytics: ^4.1.4
  flutter_localizations:
    sdk: flutter
  golden_toolkit: ^0.15.0
  network_image_mock: ^2.1.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logos/
